version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanagerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: taskmanager-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: taskmanagerdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
