version: '3.9'

services:
  db:
    image: postgres:16
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskmanagerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d taskmanagerdb"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - tasknet

  backend:
    build: ./backend
    container_name: taskmanager-backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: taskmanagerdb
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    networks:
      - tasknet

volumes:
  postgres_data:

networks:
  tasknet:
    driver: bridge
